version: '3.9'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app                 
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: clicktest
      DB_HOST: db
      DB_PORT: 5432

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: clicktest
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: